### ISSUE TITLE
refactor MLHMM / baum_welch

### ISSUE THREAD

**Issue by franknoe** [choderalab/bhmm#12]
MLHMM / baum_welch are redundant and should be refactored:
- MLHMM._transitionMatrixMLE is probable not used and definitely not needed
- MLHMM._generateInitialModel is not just a call and go to the init method
- MLHMM only delegates the work to baum_welch, so perhaps the content of baum_welch can be migrated into MLHMM

**Comment by jchodera** [comment]
We should definitely eliminate redundancy and dead code.

Regarding refactoring: we should try to make the code as close to the
structure documented in the paper as possible. Optimally this would be to
move functions into MLHMM, and have readable Python fallback
implementations of anything that calls out to C code.

**Comment by franknoe** [comment]
I agree. I'll take care of it.

Am 17/03/15 um 14:36 schrieb John Chodera:

> We should definitely eliminate redundancy and dead code.
> 
> Regarding refactoring: we should try to make the code as close to the
> structure documented in the paper as possible. Optimally this would be to
> move functions into MLHMM, and have readable Python fallback
> implementations of anything that calls out to C code.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/choderalab/bhmm/issues/12#issuecomment-82355838.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
done
