### ISSUE TITLE
examples/p5ab-hairpin broken

### ISSUE THREAD

**Issue by jchodera** [choderalab/bhmm#28]
`python generate-figure.py` generates the following error:

```
output model:
--------------------------------------------------------------------------------
GaussianOutputModel
nstates: 3
means: [ 13.84940002  12.54858602  13.01613252]
sigmas: [ 0.21264276  0.20973714  0.2004431 ]
--------------------------------------------------------------------------------

14:50:12 INFO BHMM: Elapsed time for Baum-Welch solution: 3.651 s
14:50:12 INFO BHMM: Computing Viterbi path:
14:50:12 INFO BHMM: Elapsed time for Viterbi path computation: 0.010 s
14:50:12 INFO BHMM: =================================================================
Initializing BHMM and running with 100 samples.
Traceback (most recent call last):
  File "generate-figure.py", line 86, in <module>
    run(args.nstates, args.nsamples)
  File "generate-figure.py", line 53, in run
    sampler = bhmm.BayesianHMMSampler(O, nstates, initial_model=mle)
AttributeError: 'module' object has no attribute 'BayesianHMMSampler'
```

This example is needed for the paper, so we need this one to work.

**Comment by jchodera** [comment]
Same issue with `examples/rnase-h-d10a`: `python generate-figure.py` gives the error:

```
14:51:28 INFO BHMM: =================================================================
Initializing BHMM and running with 100 samples.
Traceback (most recent call last):
  File "generate-figure.py", line 83, in <module>
    run(args.nstates, args.nsamples)
  File "generate-figure.py", line 49, in run
    sampler = bhmm.BayesianHMMSampler(O, nstates, initial_model=mle)
AttributeError: 'module' object has no attribute 'BayesianHMMSampler'
```

**Comment by jchodera** [comment]
Same thing with `examples/synthetic-three-state-model`:

```
14:52:33 INFO BHMM: =================================================================
Sampling models from BHMM...
Traceback (most recent call last):
  File "generate-figure.py", line 95, in <module>
    run(args.nstates, args.nsamples)
  File "generate-figure.py", line 64, in run
    sampler = bhmm.BayesianHMMSampler(O, nstates, initial_model=mle)
AttributeError: 'module' object has no attribute 'BayesianHMMSampler'
```

**Comment by jchodera** [comment]
Looks like you changed the naming of the interfaces at some point:
from bhmm.estimators.bayesian_sampling import BayesianHMMSampler as BHMM

**Comment by jchodera** [comment]
It was in this commit 14 days ago:
https://github.com/bhmm/bhmm/commit/4163825402a4520c83828a53cc44464f0054d642

**Comment by franknoe** [comment]
I'm on it. It was a side-effect of a refactor that I had one in the end 
to rename things in the API. For some reason the refactor function seems 
to spuriously rename such imports. Wait a sec...

Am 17/05/15 um 21:14 schrieb John Chodera:

> Looks like you changed the naming of the interfaces at some point:
> from bhmm.estimators.bayesian_sampling import BayesianHMMSampler as BHMM
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/28#issuecomment-102837261.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
Whoops, just saw this and started a PR (#29).  Want me to wait for you to fix things?

**Comment by jchodera** [comment]
Actually, I'm not sure what any of these classes are anymore, so I am closing my PR so you can fix.

**Comment by jchodera** [comment]
I must have merged #32 too soon---sorry about that.  Can you please mark PRs that you are still working on as "[WIP] My PR description..."?

#32 did not fix the examples.  For `examples/synthetic-three-state-model`, we have `python generate-figure.py` giving:

```
15:46:31 INFO BHMM: BHMM update iteration took 0.251 s
Traceback (most recent call last):
  File "generate-figure.py", line 95, in <module>
    run(args.nstates, args.nsamples)
  File "generate-figure.py", line 79, in run
    sampled_hmm = bhmm.SampledGaussianHMM(mle, bhmm_models)
AttributeError: 'module' object has no attribute 'SampledGaussianHMM'
```

**Comment by jchodera** [comment]
Whoops, my mistake!  I just forgot to reinstall after updating from your PR.  Sorry!
That example runs to completion now!

**Comment by franknoe** [comment]
It also generates a tex table. Check it out.

Am 17/05/15 um 21:50 schrieb John Chodera:

> Whoops, my mistake! I just forgot to reinstall after updating from 
> your PR. Sorry!
> That example runs to completion now!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/28#issuecomment-102843645.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
Working on that!  Will close this issue for now, and reopen if I notice more issues.
